<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateHealthCareEmployeesTable extends Migration
{
    /**
     * Run the migrations.
     * @return void
     */
    public function up(){
        Schema::create('health_care_employees', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('health_provider_id')->nullable();

            $table->string('profession')->nullable();
            $table->string('email')->unique();
            $table->string('password')->nullable(); #Default autogenerated

            $table->string('name')->nullable();
            $table->string('phone')->nullable();
            $table->string('employment_id')->nullable();

            $table->string('qualification')->nullable();
            $table->string('specialization')->nullable();

            $table->rememberToken();
            $table->timestamps();
        });
    }


    /**
     * Reverse the migrations.
     * @return void
     */
    public function down(){
        Schema::dropIfExists('health_care_employees');
    }


}



